name: techtrack
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_lints: ^2.0.0
  country_picker: ^2.0.21
  image_picker: ^0.8.6
  pinput: ^2.2.16
  shared_preferences: ^2.0.15
  email_validator: ^2.1.17
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.18.1
  path_provider: ^2.1.1
  google_fonts: ^6.1.0
  dio: ^5.3.3
  provider: ^6.0.5
  carousel_slider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/techtrackicon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
